fix diary
brains-tsukuba/brains_slack_bot pull request #29
Opened 2018-11-14 14:51 UTC by HikaruEgashira

## 概要/目的

#28 `brains diary`の修正

## やったこと

- 投稿を取得するクエリの変更
- 前回選出した人を抽選から除外
- 一人の場合は前回選出した人にする

## 確認したこと

- [x] userオプションの削除
- [x] `filter + [0]`の部分を`find`に変更
- [x] excludeUserの取得方法の変更
- [x] excludeUserの除外する位置を変更

2018-11-14 15:18 UTC, HasegawaYohei commented on managers/BrainsManager.js
> +        .filter(value => value.name === 'join' || value.name === 'late' )
`'late'` の後ろに空白入ってる.

2018-11-14 15:18 UTC, HasegawaYohei commented on managers/BrainsManager.js
>        const targetUser = targetSlackIds[Math.floor(Math.random() * targetSlackIds.length)];
if 挟むより, 114行目を下みたいにするほうがいいかな.
`const targetUser = targetSlackIds[Math.floor(Math.random() * targetSlackIds.length)] || { slackId: excludeUser };`

2018-11-14 15:21 UTC, HasegawaYohei commented
PR の確認したことには, 主に動作確認について書いて欲しい. 今回だったら, `brains diary` でランダムな選出ができるか, とか, 直近であたった人はちゃんと除外されているかなど.

2018-11-14 15:31 UTC, HasegawaYohei commented
あ, `excludeUser` って元の候補ユーザ配列に含まれていることが確定してないのか.
じゃあこれじゃダメだわ.

2018-11-15 01:41 UTC, HikaruEgashira commented
> あ, `excludeUser` って元の候補ユーザ配列に含まれていることが確定してないのか.
> じゃあこれじゃダメだわ.

その場合17及び18生自体がいない状況なので、
reactionUserSlackIdsを候補に入れるようにしてもよろしいですか？

2018-11-15 01:50 UTC, HasegawaYohei commented
おけい.

2018-11-15 04:50 UTC, HasegawaYohei reviewed
うーん... let や if分岐 はできるだけ多用したくないな. このケースだったら, let/if なしで実装できると思う.
ここ(GitHub上)で説明することもできなくは無いけど(だいぶ分かりづらいと思う), 今日の活動の時に説明した方がいいかな? 題材としては面白いので, みんなに共有しながらやるのはありだと思う.

2018-11-16 06:07 UTC, HasegawaYohei requested changes

2018-11-16 06:07 UTC, HasegawaYohei commented on managers/BrainsManager.js
> +      const exitLatestDiaryUser = reactionUserSlackIds.find(v => v === latestDiaryUser);
すまん, 送ったやつタイポしてた.
101行目: `exitLatestDiaryUser` じゃなくて `existLatestDiaryUser` に修正して欲しい.

2018-11-16 12:41 UTC, HasegawaYohei approved these changes

2018-11-16 12:44 UTC, HasegawaYohei commented
LGTM 🎉 
修正 & 機能追加ありがとう!! マージします!!
( プルリクのタイトルを分かりやすいものに直しといて!! )

2018-11-16 14:31 UTC, HasegawaYohei commented
すまん, ちょっと PR タイトル変えた.

2018-11-16 14:31 UTC, merged